In [1]:
import pandas as pd

In [2]:
data = pd.read_parquet("students.parquet")

In [3]:
data.sample(10)

,Student_ID,Age,Gender,Academic_Level,Country,Avg_Daily_Usage_Hours,Most_Used_Platform,Affects_Academic_Performance,Sleep_Hours_Per_Night,Mental_Health_Score,Relationship_Status,Conflicts_Over_Social_Media,Addicted_Score
94,95,23,Male,Graduate,Bosnia,2.4,LinkedIn,No,7.4,8,Complicated,1,4
199,200,22,Male,Graduate,Pakistan,4.1,Instagram,Yes,7.5,5,In Relationship,3,7
166,167,20,Female,Undergraduate,Bangladesh,4.9,Instagram,Yes,6.4,5,Single,3,7
279,280,22,Male,Graduate,Germany,3.6,Instagram,No,7.9,8,Single,1,4
378,379,20,Female,Undergraduate,France,4.0,Instagram,No,8.0,7,In Relationship,2,5
393,394,21,Male,Graduate,India,6.5,WhatsApp,Yes,5.8,5,In Relationship,4,8
236,237,19,Female,Undergraduate,USA,6.8,Instagram,Yes,5.9,4,Single,4,9
551,552,22,Male,Graduate,China,4.0,WeChat,No,8.3,7,In Relationship,2,5
173,174,21,Male,Graduate,India,5.1,Facebook,No,7.4,7,In Relationship,2,6
536,537,19,Female,Undergraduate,UAE,6.8,Instagram,Yes,6.2,5,In Relationship,4,8